### ISSUE TITLE
Timeout overflow

### ISSUE THREAD

**Issue by macedolfm** [pololu/vl53l0x-arduino#35] opened 2019-06-14 02:02 UTC
Timeout variables shall be unsigned long, so if sensor init() is called latter after MCU start up they do not overflow. This happened to me !!

uint16_t io_timeout;  => unsigned long io_timeout;
uint16_t timeout_start_ms; => unsigned long timeout_start_ms;

Also timeout functions signatures shall also be unsigned long:

inline void setTimeout(unsigned long timeout)
inline unsigned long getTimeout(void)

**Comment by kevin-pololu** [comment] 2019-06-18 21:04
This is probably a duplicate of #32. If you think it's a different problem, please reopen this issue and tell me more about your setup include what kind of Arduino you're using and what unexpected behavior you see.

**Closed by kevin-pololu** 2019-06-18 21:04 UTC
